import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
<<<<<<< HEAD
import { dbConnect } from "@/services/mongo";
import AuthProvider from "./providers/AuthProvider";
=======
>>>>>>> 8cca44e263f893e86199b6f188d5b0ef614e2b64

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <main className="py-8">{children}</main>
        </body>
      </AuthProvider>
=======
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="py-8">{children}</main>
      </body>
>>>>>>> 8cca44e263f893e86199b6f188d5b0ef614e2b64
    </html>
  );
}
